# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 2.7
        env: TOXENV=py27
      - python: 3.4
        env: TOXENV=py34
      - python: 3.5
        env: TOXENV=py35
      - python: 3.6
        env: TOXENV=py36
      - python: 3.7
        env: TOXENV=py37
        sudo: true    # Required for Python 3.7
        dist: xenial  # Required for Python 3.7
      - python: pypy
        env: TOXENV=pypy
      - python: 3.7
        env: TOXENV=flake8
        sudo: true    # Required for Python 3.7
        dist: xenial  # Required for Python 3.7

install: pip install tox

script: tox

after_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - pip install codecov
    - codecov -e TOXENV TRAVIS_OS_NAME
