
name: 🐞 Bug Report
title: '🐞 '
description: Report a bug
labels: ['type: bug', 'status: needs triage']

body:
  - type: markdown
    attributes:
      value: |
        Please search for [existing issues](https://github.com/cookiecutter/cookiecutter/issues?q=is%3Aissue) about this problem first.

  - type: input
    id: cookiecutter-version
    attributes:
      label: Cookiecutter version
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
    validations:
      required: true

  - type: input
    id: template-project-url
    attributes:
      label: Template project URL
      description: URL to the project template with which the bug happens

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What are you trying to get done, what has happened, what went wrong, and what did you expect?
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a reproduction repo or steps to reproduce the behaviour.
      placeholder: |
        Paste a log of command(s) you ran and cookiecutter's output, tracebacks, etc, here

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
