name: "Documentation build check"
on:
  pull_request:
    branches:
      - "*"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ammaraskar/sphinx-action@0.4
        with:
          pre-build-command: "pwd && pip install . && pip install -r test_requirements.txt"
          docs-folder: "docs/"
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
